services:
  type: web
  name: login-backend-api
  runtime: java
  plan: free
  buildCommand: mvn clean package -DskipTests
  startCommand: java -jar target/login-backend-*.jar
  envVars:
    - key: SPRING_DATASOURCE_URL
      sync: false
      value: jdbc:postgresql://databases:5432/render_db
    - key: SPRING_DATASOURCE_USERNAME
      sync: false
      value: render_user
    - key: SPRING_DATASOURCE_PASSWORD
      sync: false
      value: render_password
    - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      sync: false
      value: update
    - key: JWT_SECRET
      sync: false
      value: tu_clave_secreta_super_segura_12345678901234567890
