spring.application.name=login-backend

# Configuracion MySQL (ajusta con tus datos reales)
spring.datasource.url=jdbc:mysql://localhost:3306/usuarios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuracion JWT
jwt.secret=MI_CLAVE_SUPER_SECRETA_LARGA_32_CHARS_MIN_2026
jwt.expiration=3600000
